version: '2'
services:
  specjserver:
    image: specjserver
    container_name: specjserver
    ports:
    - "4848:4848"
    - "8080:8080"
    - "8181:8181"
    #volumes: if required
  specjfaban:
    image: specjfaban
    container_name: specjfaban
    ports:
    - "9980:9980"
    depends_on:
      - specjserver
